import { Lora } from 'next/font/google'
import './globals.css'

const typeface = Lora({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={typeface.className}>{children}</body>
    </html>
  )
}
